### ISSUE TITLE
Long shot. I think you are the only person who can help me.

### ISSUE THREAD

**Issue by enoquelights** [Sunoyon/face-recognition#1]
Hello,

I know this is an old project and I apologize for resurrecting it. I am trying to use your code in conjunction with CUDA, I am using a mix between your app and the cuda dockerfile on face_recognition github and run into an issue and I dont know how to solve it. The scripts in tests run fine, but when using the API I get:
RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /opt/app/dlib/dlib/cuda/gpu_data.cpp:204. code: 3, reason: initialization error

Since the tests run fine without errors, i guess i am missing something else that needs doing. Is there anything you can think of that need changing in your code that might solve this?

The Docker file:

 ```
FROM nvidia/cuda:12.8.0-cudnn-devel-ubuntu22.04

RUN apt-get -y --fix-missing update
RUN apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    python3-pip \
    python3-numpy \
    software-properties-common \
    zip \
    vim \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libxml2 
RUN apt-get clean && rm -rf /tmp/* /var/tmp/*
RUN apt update
RUN add-apt-repository ppa:ubuntu-toolchain-r/test -y
RUN pip3 install scikit-build
RUN apt update -y
RUN apt install -y gcc-12 
RUN apt install -y g++-12
WORKDIR /opt/app
RUN mkdir -p /opt/app
RUN git clone https://github.com/enoquelights/face-recognition.git /opt/app
RUN git clone -b 'v20.0' --single-branch https://github.com/davisking/dlib.git
RUN mkdir -p /opt/app/dlib/build

RUN cmake -H/opt/app/dlib -B/opt/app/dlib/build -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
RUN cmake --build /opt/app/dlib/build

RUN cd /opt/app/dlib; python3 /opt/app/dlib/setup.py install

RUN pip install --upgrade pip setuptools wheel
RUN pip install git+https://github.com/enoquelights/face_recognition_models
RUN pip3 install --upgrade pip && pip install --ignore-installed marshmallow==3.26.1 Flask-SQLAlchemy==3.1.1 Flask==3.1.1 Flask-rebar==3.3.2 python-dotenv==1.1.0 psycopg2-binary==2.9.10 uWSGI==2.0.30
RUN pip install face_recognition
```

The Compose:
```
face-recognition-cuda:
    image: facecuda12:1
    ports:
      - 5024:5001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
                  
    environment:    
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
      APP_CONFIG: /opt/app/app/config/prod.cfg
    volumes:
      - /media/media2/config/dlib/logs:/var/log/face-recognition/
      - /media/media2/config/dlib/models:/tmpmods/
    command: "sh /opt/app/entrypoint.sh"
```

Output from CUDA version within the container. GPU is enabled.

```
root@e9fb31dd4397:/opt/app# nvidia-smi       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.20             Driver Version: 570.133.20     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660        Off |   00000000:01:00.0 Off |                  N/A |
| 38%   36C    P8              8W /  120W |    5627MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A              25      C   uwsgi                                   112MiB |
+-----------------------------------------------------------------------------------------+
root@e9fb31dd4397:/opt/app# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0
```
